config/routes.rb
Rails.application.routes.draw do

  root to: 'users#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :trip_routes
  resources :articles, only: [:index, :show, :create] do
    resources :comments
    resources :article_photos, only: [:index, :new, :create, :destroy]
  end
  resources :article_photos, only: [:new, :create, :destroy]
  resources :places do
    resources :place_photos, only: [:index, :new, :create, :destroy]
  end
  get 'user_places', to: 'places#user_places'
 
  get 'search_trip_routes', to: 'trip_routes#search'
  get 'search_places', to: 'places#search'
  get 'user_routes', to: 'trip_routes#user_routes'
  get 'take_trip/:id', to: 'trip_routes#take_trip', as: :take_trip  
  post 'update_trip_places', to: 'trip_routes#update_trip_places'

  get 'users_list', to: 'users#list_users', as: :people
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'my', to: 'users#current_user_page'
  resources :users do
    resources :photos, only: [:index, :new, :create, :destroy]
    resources :articles do
      resources :comments
    end
  end

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
end

app/models/trip_route.rb
class TripRoute < ApplicationRecord
  belongs_to :user
  has_many :trip_route_places, dependent: :destroy
  has_many :user_selected_routes, dependent: :destroy
  has_many :places, through: :trip_route_places
  has_many :trip_route_articles, dependent: :destroy
  has_many :articles, through: :trip_route_articles
  has_many :trip_route_photos, dependent: :destroy
  has_many :photos, through: :trip_route_photos
  
  scope :title_includes, -> (search_string) {
    where('lower(name) like ?', "%#{search_string}%".downcase)
  }

  scope :distance_length, -> (min_distance, max_distance) {
    where(distance: min_distance..max_distance)
  }

  scope :duration_length, -> (min_duration, max_duration) {
    where(duration: min_duration..max_duration)
  }

  scope :places_count, -> (min_count, max_count) {
    includes(:trip_route_places).all.select{|trip_route| trip_route.trip_route_places.count.in?((min_count.to_i..max_count.to_i).to_a)}
  }

  def places_to_visit
    place_ids.collect{ |p| [p, false] }.to_h
  end

  def places_ordered
    places.includes(:trip_route_places).order('trip_route_places.waypoint_nr')
  end

  def completed?
    places.where(visited: false).empty?
  end

  def photos
    places.select{|place| !place.photos.empty? }.collect do |place|
      !place.photos.empty? ? place.photos.first : next 
    end
  end
  
  private

  def add_achievment_points_to_user
    places_ach_variable = Variable.find_by_name('created_routes')
    user_variable = user.user_variables.where(variable: places_ach_variable).first_or_create
    user_variable.value += 1
    user_goals = AchievmentGoal.where(variable_id: places_ach_variable.id, goal: user_variable.value)
    user_variable.save!
    if user_goals.present?
      user_goals.each do |user_goal|
        user_achievment = user.user_achievments.create!(achievment: user_goal.achievment)
        AchievmentRelayJob.perform_now(user_achievment)
      end
    end
  end
end

app/controllers/trip_routes_controller.rb
class TripRoutesController < ApplicationController
  before_action :set_trip_route, only: [:show, :edit, :update, :destroy, :take_trip]
  before_action :trip_route_places, only: [:create, :update]
  before_action :set_place_types, only: [:new, :edit]

  has_scope :title_includes
  has_scope :distance_length, using: [:min_distance, :max_distance], type: :hash
  has_scope :duration_length, using: [:min_duration, :max_duration], type: :hash
  has_scope :places_count, using: [:min_count, :max_count], type: :hash

  # GET /trip_routes
  # GET /trip_routes.json
  def index
    @trip_routes = apply_scopes(TripRoute).all.order(created_at: :desc)
  end

  def search
    @trip_routes = apply_scopes(TripRoute) #.where("1=1")
  end

  def user_routes
    @user_selected_routes = current_user.selected_routes
    @trip_routes = current_user.trip_routes
  end
  # GET /trip_routes/1
  # GET /trip_routes/1.json
  def show
    @articles = @trip_route.articles
    @article = Article.new
    @trip_route_places = @trip_route.places_ordered.collect.with_index { |place, index|
      view_context.link_to("#{index + 1} #{place.name}", place_path(place))
    }.join(', ')
  end

  def take_trip
    @route = current_user.user_selected_routes
      .where(trip_route_id: @trip_route.id)
      .first_or_create!(
        places: @trip_route.places_to_visit
      )
    respond_to :html, :json
  end

  def update_trip_places;  end

  # GET /trip_routes/new
  def new
    @trip_route = TripRoute.new
  end

  # GET /trip_routes/1/edit
  def edit
  end

  # POST /trip_routes
  # POST /trip_routes.json
  def create
    @trip_route = TripRoute.new(trip_route_params)

    @trip_route.user = current_user
    respond_to do |format|
      if @trip_route.save
        @places.each_with_index do |place, order_nr|
          @trip_route.trip_route_places.create!(place: place, waypoint_nr: order_nr)
        end    

        format.html { redirect_to @trip_route, notice: 'Trip route was successfully created.' }
        format.json { render :show, status: :created, location: @trip_route }
      else
        format.html { render :new }
        format.json { render json: @trip_route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trip_routes/1
  # PATCH/PUT /trip_routes/1.json
  def update
    # @trip_route.places = @places
    @trip_route.places.delete_all

    @places.each_with_index do |place, order_nr|
      @trip_route.trip_route_places.create!(place: place, waypoint_nr: order_nr)
    end

    respond_to do |format|
      if @trip_route.update(trip_route_params)
        format.html { redirect_to @trip_route, notice: 'Trip route was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip_route }
      else
        format.html { render :edit }
        format.json { render json: @trip_route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trip_routes/1
  # DELETE /trip_routes/1.json
  def destroy
    @trip_route.destroy
    respond_to do |format|
      format.html { redirect_to trip_routes_url, notice: 'Trip route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_place_types
      @place_types = []
      pts = PlaceType.all
      pts.each { |place_type|
        @place_types.push(place_type) unless place_type.places.blank? 
      }
      @place_types
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_trip_route
      @trip_route = TripRoute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_route_params
      params.require(:trip_route).permit(:name, :duration, :distance)
    end

    def trip_route_places
      @places_ids = params.require(:places).split(',').map{|place_id| place_id.to_i}
      @places = Place.find(@places_ids)
    end
end

app/helpers/trip_routes_helper.rb
module TripRoutesHelper
end

app/views/trip_routes/partials/_route_card.html.erb
<% editable = editable.present? ? editable : false %>
<div class="card">
  <div class="card-divider">
    <%= link_to trip_route.name, trip_route_path(trip_route) %>
  </div>
  <% if trip_route.photos.present? %>
    <div class="owl-carousel trip-route-gallery">
      <% trip_route.photos.each do |photo| %>
        <div class="item">
          <%= image_tag photo.image.url(:medium) %>
        </div>
      <% end %>
    </div>        
  <% end %>
  <div class="card-section">
    <div class="row">
      <div class="small-6 columns">
        <i class="fi-foot medium"></i>&nbsp;
        <span><%= trip_route.distance %>&nbsp;km</span>
      </div>
      <div class="small-6 columns">
        <i class="fi-clock medium"></i>&nbsp;
        <span><%= trip_route.duration %>&nbsp;min</span>
      </div>
    </div>
    <div class="row">
      <div class="small-6 columns">
        <i class="fi-mountains medium"></i>&nbsp;
        <span><%= trip_route.places.count %></span>
      </div>
      <div class="small-6 columns">       
      </div>
    </div>
    <div class="row">
      <div class="small-6 columns">
      <% unless editable %>
        <%= link_to trip_route_path(trip_route), class: :button do %>
          Plačiau
        <% end %>
        <% else %>
        <%= link_to edit_trip_route_path(trip_route), class: :button do %>
          Redaguoti
        <% end %>
      <% end %>
      </div>
      <div class="small-6 columns">
        <%= link_to take_trip_path(trip_route), class: :button do %>
          Keliauti
        <% end %>
      </div>
    </div>
    <p><small>Sukurtas: <%= trip_route.user.name %></small></p>    
  </div>
</div>

app/views/trip_routes/partials/_route_plan_table.html.erb
<ul class="accordion"
  data-accordion
  data-allow-all-closed="true">
  <li class="accordion-item"
    data-accordion-item>
    <%= link_to 'Kelionės maršrutas', '#', class: 'accordion-title' %>
    <div class="accordion-content" data-tab-content>
      <ul class="list-group"
        id="route-plan-list">
        <% unless @trip_route.places.blank? %>
          <% @trip_route.places.each do |route_place| %>
            <li class="list-group-item place__info route-plan-item"
              data-place-name="<%= route_place.name %>"
              data-place-id="<%= route_place.id %>"
              data-place-type-id="<%= route_place.place_type.id %>"
              data-place-position-lat="<%= route_place.latitude %>"
              data-place-position-lng="<%= route_place.longitude %>">
              <div class="row">
                <div class="small-2 columns plan-item-handler">
                  <%= link_to '#' do %>
                    <span><i class="fi-paw medium"></i></span>
                  <% end %>
                </div>
                <div class="small-8 columns place-name">
                  <%= route_place.name %>
                </div>
                <div class="small-2 columns plan-item-remove">
                  <button data-behaviour="remove-selected-place"><i class="fi-x small"></i></button>
                </div>
              </div>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </li>
  <% @place_types.each do |place_type| %>
    <% all_places = place_type.places_not_associated_with_route(@trip_route) %>
    <% unless all_places.blank? %>
      <li class="accordion-item place-type"
        data-place-type-id="<%= place_type.id %>"
        data-accordion-item>
        <%= link_to place_type.name.capitalize, '#', class: 'accordion-title' %>
        <div class="accordion-content place-type-content" data-tab-content>
          <div class="row place-type-places">
            <% all_places.each do |place| %>
              <div class="small-6 columns place-info"
                data-place-name="<%= place.name %>"
                data-place-id="<%= place.id %>"
                data-place-type-id="<%= place_type.id %>"
                data-place-position-lat="<%= place.latitude %>"
                data-place-position-lng="<%= place.longitude %>">
                <div class="card">
                  <div class="card-section">
                    <div class="row columns">
                      <%= place.name.split(' ')[0] %>
                    </div>
                    <div class="row">
                      <div class="columns">
                        <%= button_tag data: { behaviour: :add__place } do %>
                          <i class="fi-check"></i>
                        <% end %>
                      </div>
                      <!-- <div class="columns">
                        <% button_tag do %>
                          <i class="fi-x"></i>
                        <% end %>
                      </div>
                      <div class="columns">
                        <% button_tag do %>
                          <i class="fi-list"></i>
                        <% end %>
                      </div> -->
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/trip_routes/partials/_search_form.html.erb
<div class="callout is-hidden" id="form-callout" data-toggler="is-hidden">
<%= form_tag search_trip_routes_path, method: :get do %>
<%= label_tag 'Pavadinimas' %>
<%= text_field_tag :title_includes, '' %>

<div class="row">
  <div class="small-12 medium-4 columns">
    <%= label_tag 'Vietų skaičius' %>
    <div class="row">
      <div class="small-6 columns">
        <%= text_field_tag 'places_count[min_count]', params['places_count[min_count]'], type: :number, id: 'places-count-min' %>
      </div>
      <div class="small-6 columns">
        <%= text_field_tag 'places_count[max_count]', params['places_count[max_count]'], type: :number, id: 'places-count-max' %>
      </div>
    </div>
    <div class="row">
      <div class="columns">
        <div class="slider" data-slider  data-start="0" data-initial-start="1" data-initial-end="25" data-end="25">
          <span class="slider-handle" data-slider-handle role="slider" tabindex="1" aria-controls="places-count-min"></span>
          <span class="slider-fill" data-slider-fill></span>
          <span class="slider-handle" data-slider-handle role="slider" tabindex="1" aria-controls="places-count-max"></span>
        </div>
      </div>
    </div>
  </div>
  <div class="small-12 medium-4 columns">
    <%= label_tag 'Maršruto ilgis (km)' %>
    <div class="row">
      <div class="small-6 columns">
        <%= text_field_tag 'distance_length[min_distance]', params['distance_length[min_distance]'], type: :number, id: 'distance-min' %>
      </div>
      <div class="small-6 columns">
        <%= text_field_tag 'distance_length[max_distance]', params['distance_length[max_distance]'], type: :number, id: 'distance-max' %>
      </div>
    </div>
    <div class="row">
      <div class="columns">
        <div class="slider" data-slider  data-start="0" data-initial-start="1" data-initial-end="1500" data-end="1500">
          <span class="slider-handle" data-slider-handle role="slider" tabindex="1" aria-controls="distance-min"></span>
          <span class="slider-fill" data-slider-fill></span>
          <span class="slider-handle" data-slider-handle role="slider" tabindex="1" aria-controls="distance-max"></span>
        </div>
      </div>
    </div>
  </div>
  <div class="small-12 medium-4 columns">
  <%= label_tag 'Maršruto trukmė (min)' %>
    <div class="row">
      <div class="small-6 columns">
        <%= text_field_tag 'duration_length[min_duration]', params['duration_length[min_duration]'], type: :number, id: 'duration-min' %>
      </div>
      <div class="small-6 columns">
        <%= text_field_tag 'duration_length[max_duration]', params['duration_length[max_duration]'], type: :number, id: 'duration-max' %>
      </div>
    </div>
    <div class="row">
      <div class="columns">
        <div class="slider" data-slider data-start="0" data-initial-start="1" data-initial-end="2000" data-end="2000">
          <span class="slider-handle" data-slider-handle role="slider" tabindex="1" aria-controls="duration-min"></span>
          <span class="slider-fill" data-slider-fill></span>
          <span class="slider-handle" data-slider-handle role="slider" tabindex="1" aria-controls="duration-max"></span>
        </div>
      </div>
    </div>
  </div>
</div>
  <%= link_to 'Rodyti visus', trip_routes_path, class: :button %>
  <%= submit_tag 'Ieškoti', class: :button %>
<% end %>
</div>

<p><a data-toggle="form-callout" class="button">Paieška</a></p>

app/views/trip_routes/partials/_selected_route_place_reveal.html.erb
<button class="close-button" data-close aria-label="Close modal" type="button">
  <span aria-hidden="true">&times;</span>
</button>
<% unless completed %>
  <% unless visited %>
    <p>Žymėti kaip aplankytą?</p>
  <% else %>
    <p>Žymėti kaip neaplankytą?</p>
  <% end %>
  <%= link_to('Taip',
              update_trip_places_path,
              class: 'small button',
              data: {
                  'behaviour': 'update-trip-places',
                  'place-id': place.id,
                  'place-visited': visited,
                  'selected-route-id': selected_route_id
              }
      ) %>
  <% else %>
  <p>Sveikinam įveikus maršrutą</p>
  <%= link_to('Grįžti į pagrindinį puslapį',
            root_path,
            class: 'small button'
           ) %>   
<% end %>

app/views/trip_routes/partials/_trip_routes_content.html.erb
<div class="row columns">
  <div class="callout">
    <br><div class="row">
      <div class="small-12 medium-6"><h3>Maršrutai</h3></div>
      <div class="small-12 medium-3"><%= link_to 'Mano maršrutai', user_routes_path, class: 'small button' %></div>
      <div class="small-12 medium-3"><%= link_to 'Pridėti maršrutą', new_trip_route_path, class: 'small button' %></div>
    </div>

    <% unless @trip_routes.empty? %>
    <div class="callout">
      <div class="row columns">
        <%= render 'trip_routes/partials/search_form' %>
      </div>

      <div class="row">
        <% @trip_routes.each do |trip_route| %>
          <div class="small-8 small-offset-2 medium-offset-0 large-offset-0  medium-4 large-3">
            <%= render 'trip_routes/partials/route_card', trip_route: trip_route %>
          </div>
        <% end %>
      </div>
    </div>
    <% else %>
      <h4>Nėra sukurtų maršrutų</h4>
    <% end %>    
  </div>
</div>

app/views/trip_routes/partials/_trip_routes_grid.html.erb
<div class="orbit" role="region" aria-label="Trip Routes" data-orbit data-timer-delay="5000">
  <ul class="orbit-container">
    <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
    <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
    <% trip_routes.each_with_index do |trip_route, index| %>
      <li class="<%= 'is_active' if index == 0 %> orbit-slide">
      <div class="callout">
        <div class="row">
          <div class="small-12 column align-self-middle text-center">
            <h3><%= trip_route.name %></h3>
            <% if trip_route.photos.present? %>
              <div class="middle">
                <div class="owl-carousel trip-route-main-photos">
                  <% trip_route.photos.each do |photo| %>
                    <div class="item thumbnail">
                      <%= image_tag photo.image.url(:panoram) %>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
        </div>
      </li>      
    <% end %>
  </ul>
  <nav class="orbit-bullets">
    <% trip_routes.each_with_index do |trip_route, index| %>
      <% if index == 0 %>
        <button class="is_active" data-slide="<%= index %>">
          <span class="show-for-sr"><%= index %><%= index %>slide details.</span>
          <span class="show-for-sr">Current Slide</span>
        </button>
      <% else %>
        <button data-slide="<%= index %>">
          <span class="show-for-sr"><%= index %> slide details.</span>
        </button>
      <% end %>
    <% end %>
  </nav>
</div>

app/views/trip_routes/partials/_visited_button.html.erb
<p>
  <a data-open="place-modal<%= place.id %>" data-turbolinks="false" class="small button">
    <% unless visited %>
        <i class="fi-check"></i>
    <% else %>
        <i class="fi-x"></i>
    <% end %>
  </a>
</p>