config/routes.rb
Rails.application.routes.draw do

  root to: 'users#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :trip_routes
  resources :articles, only: [:index, :show, :create] do
    resources :comments
    resources :article_photos, only: [:index, :new, :create, :destroy]
  end
  resources :article_photos, only: [:new, :create, :destroy]
  resources :places do
    resources :place_photos, only: [:index, :new, :create, :destroy]
  end
  get 'user_places', to: 'places#user_places'
 
  get 'search_trip_routes', to: 'trip_routes#search'
  get 'search_places', to: 'places#search'
  get 'user_routes', to: 'trip_routes#user_routes'
  get 'take_trip/:id', to: 'trip_routes#take_trip', as: :take_trip  
  post 'update_trip_places', to: 'trip_routes#update_trip_places'

  get 'users_list', to: 'users#list_users', as: :people
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'my', to: 'users#current_user_page'
  resources :users do
    resources :photos, only: [:index, :new, :create, :destroy]
    resources :articles do
      resources :comments
    end
  end

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_comments, dependent: :destroy
  has_many :comments, through: :article_comments, dependent: :destroy
  has_many :article_photos, dependent: :destroy
  has_one :trip_route_article, dependent: :destroy
  has_one :trip_route, through: :trip_route_article

  enum topic: {general: 0, triproute: 1, place: 2}

  def photos
    article_photos
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]

  def index
    @articles = Article.all.order(updated_at: :desc)
  end

  def show
  end

  def create
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="callout">
<div class="row">
  <div class="small-12 column align-self-middle text-center">
    <h3><%= article.title %><small><%= article.updated_at.strftime('%R %D') %></small></h3>
      <% if article.photos.present? %>
        <div class="media-object-section middle">
        <div class="owl-carousel article-photos">
          <% article.photos.each do |photo| %>
            <div class="item">
              <%= image_tag photo.image.url(:panoram) %>
            </div>
          <% end %>
        </div>
        </div>
      <% end %>
    <p><%= article.body %></p>
    <div class="callout">
      <ul class="menu simple">
        <li><%= link_to 'Daugiau', article_path(article) %></li>
        <li><%= link_to "Autorius: #{article.user.name}", '#' %></li>
        <li><%= link_to "Komentarai: #{article.comments.count}", '#' %></li>
      </ul>
    </div>
  </div>
</div>
</div>

app/views/articles/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <div data-behaviour="new__post">
      <%= render 'articles/partials/new_article', article: @article, article_type: ArticleType::SIMPLE, param: {} %>
    </div>
  </div>
</div>
<div class="row">
  <div class="small-12 columns">
<div class="callout">
  <div data-behaviour="articles-list">
    <% @articles.each_with_index do |article, index| %>
      <%= render article %>    
    <% end %>
  </div>
</div>
</div>
</div>

app/views/articles/show.html.erb
<div class="callout">
  <div class="row">
    <div class="small-12 column align-self-middle text-center">
      <h3><%= @article.title %></h3><h5><small><%= @article.updated_at.strftime('%R %D') %></small></h5>
        <% if @article.photos.present? %>
          div.row.>columns
          <div class="middle">
            <div class="owl-carousel article-photos">
              <% @article.photos.each do |photo| %>
                <div class="item">
                  <%= image_tag photo.image.url(:panoram) %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <p><%= @article.body %></p>
      <hr>
      <h5 class="text-left"><small>Komentarai:</small></h5>
      <div id="article-comments">
      <% unless @article.comments.empty? %>
        <% @article.comments.reverse.each do |comment| %>
          <%= render partial: 'comments/partials/comment', locals: {comment: comment} %>
        <% end %>
      <% end %>
        <%= form_for [current_user, @article, Comment.new], data: {'article-id': @article.id} do |f| %>
          <%= f.text_field :body, placeholder: 'Tavo komentaras' %>
        <% end %>
      </div>
    </div>
    </div>
  </div>
</div>