config/routes.rb
Rails.application.routes.draw do

  root to: 'users#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :trip_routes
  resources :articles, only: [:index, :show, :create] do
    resources :comments
    resources :article_photos, only: [:index, :new, :create, :destroy]
  end
  resources :article_photos, only: [:new, :create, :destroy]
  resources :places do
    resources :place_photos, only: [:index, :new, :create, :destroy]
  end
  get 'user_places', to: 'places#user_places'
 
  get 'search_trip_routes', to: 'trip_routes#search'
  get 'search_places', to: 'places#search'
  get 'user_routes', to: 'trip_routes#user_routes'
  get 'take_trip/:id', to: 'trip_routes#take_trip', as: :take_trip  
  post 'update_trip_places', to: 'trip_routes#update_trip_places'

  get 'users_list', to: 'users#list_users', as: :people
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'my', to: 'users#current_user_page'
  resources :users do
    resources :photos, only: [:index, :new, :create, :destroy]
    resources :articles do
      resources :comments
    end
  end

  resources :chatrooms do
    resource :chatroom_users
    resources :messages
  end
end

app/models/place.rb
class Place < ApplicationRecord
  paginates_per 50
  belongs_to :user
  belongs_to :place_type
  has_many :trip_route_places, dependent: :destroy
  has_many :trip_routes, through: :trip_route_places
  has_many :place_tags
  has_many :tags, through: :place_tags
  has_many :place_photos, dependent: :destroy

  attr_accessor :visited

  scope :title_includes, -> (search_string) {
    where('lower(name) like ? or lower(description) like ?',
      "%#{search_string}%".downcase, "%#{search_string}%".downcase
      )
  }
  scope :type, -> (type_id) {
    where(place_type_id: type_id)
  }

  after_create :add_achievment_points_to_user, :set_default_photo

  def photos
    place_photos
  end

  def remove_default_photo
    photos.where(image_file_name: File.basename(default_image_path)).destroy_all
  end

  private

  def add_achievment_points_to_user
    places_ach_variable = Variable.find_by_name('created_places')
    user_variable = user.user_variables.where(variable: places_ach_variable).first_or_create
    user_variable.value += 1
    user_goals = AchievmentGoal.where(variable_id: places_ach_variable.id, goal: user_variable.value)
    user_variable.save!
    if user_goals.present?
      user_goals.each do |user_goal|
        user_achievment = user.user_achievments.create!(achievment: user_goal.achievment)
        AchievmentRelayJob.perform_now(user_achievment)
      end
    end
  end

  def default_image_path
    "#{Rails.root}/public/static_assets/default_place.png"
  end

  def set_default_photo
    ph_file = File.open(default_image_path)
    place_photos.create!(image: ph_file)
    ph_file.close
  end
end

app/models/place_type.rb
class PlaceType < ApplicationRecord
  has_many :places

  def places_not_associated_with_route(route)
    places.where.not(id: route.place_ids)   
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  before_action :set_place_types, only: [:new, :edit]
  has_scope :title_includes, :type
  # GET /places
  # GET /places.json
  def index
    @page_places = apply_scopes(Place).all.order(created_at: :desc).page(params[:page]).per(8)
    @places = apply_scopes(Place).all
  end

  def search
    @page_places = apply_scopes(Place).all.page(params[:page]).per(8)
    @places = apply_scopes(Place).all
  end
  # GET /places/1
  # GET /places/1.json
  def show
  end

  def user_places
    @places = current_user.places
  end
  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    @place.user = current_user
    @place.place_type = PlaceType.find(params[:place][:place_type_id])
    respond_to do |format|
      if @place.save        
        format.html { redirect_to place_place_photos_path(@place), notice: 'Place was successfully created.' }
        # format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to place_place_photos_path(@place), notice: 'Place was successfully created.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :description, :longitude, :latitude, :place_type_id)
    end

    def set_place_types
      @place_types = PlaceType.all
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/partials/_place_callout.html.erb
<div class="callout">
  <div class="row">
    <div class="small-12 column align-self-middle text-center">
      <h3><%= place.name %></h3>
        <% if place.photos.present? %>
          <div class="media-object-section middle">
            <div class="thumbnail">
              <%= image_tag place.photos.first.image.url(:panoram) %>
            </div>
          </div>
        <% end %>
      <p><%= place.description %></p>
      <div class="callout">
        <ul class="menu simple">
          <li><%= link_to 'Daugiau', place_path(place) %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/places/partials/_places_grid.html.erb
<div class="owl-carousel owl-theme" id="places__grid">
  <% places.each do |place| %>
    <div class="card" style="width: 99%; height: auto;">
      <div class="card-divider">
        <%= place.name.shorten(2) %>
      </div>       
      <div style="max-width: 280px;height: auto;">
      <% unless place.photos.blank? %>
        <%= image_tag place.photos.first.image.url %>
      <% else %>
        <%= image_tag 'default_place.png' %>
      <% end %>
      </div>
      <div class="card-section"><hr>
        <p><%= link_to 'Daugiau', place_path(place), class: 'button' %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/places/partials/_search_form.html.erb
<div class="callout is-hidden" id="form-callout" data-toggler="is-hidden">
  <%= form_tag search_places_path, method: :get do %>
    <div class="row">
      <div class="small-12 medium-8 columns">
        <%= label_tag 'Pavadinimas' %>
        <%= text_field_tag :title_includes, '' %>
      </div>
      <div class="small-12 medium-4 columns">
        <%= label_tag 'Tipas' %>
        <%= select_tag :type, options_from_collection_for_select(PlaceType.all, "id", "name") %>
      </div>
    </div>


    <%= link_to 'Rodyti visas', places_path, class: :button %>
    <%= submit_tag 'Ieškoti', class: :button %>
  <% end %>
</div>

<p><a data-toggle="form-callout" class="button">Paieška</a></p>